evaluation:
  evaluation:
    evaluation_fn: "@factor_vae_score"
    random_seed: 0
  dataset:
    name: "\"auto\""
  # beta_vae_sklearn:
  #   batch_size: 64
  #   num_train: 10 #10000
  #   num_eval: 5 #5000
  # dci:
  #  num_train: 10000
  #  num_test: 5000
  factor_vae_score:
    num_variance_estimate: 10000
    num_train: 10000
    num_eval: 5000
    batch_size: 64
  # hsic:
  #   sigma: [10,100,1000]
  #   num_sample_reparam: 30
  #   num_points: 256
  #   batch_size: 64
  prune_dims:
    threshold: 0.05

postprocess:
  postprocess:
    random_seed: 0
    postprocess_fn: "@mean_representation"
  dataset:
    name: "\"auto\""
# train:
#   model:
#     # name: "HsicBetaVAE"
#     batch_size: 64
#     model: "@HsicBetaVAE()"  #"@vae()"
#     training_steps: 5 #100000
  # HsicBetaVAE:
  #   alpha: 100
  #   beta: 4
  #   s_x: 100
  #   s_y: 100
  #   num_sample_reparam: 3
train:
  model:
    name: "\"dip_vae_ii\"" #"HsicBetaVAE"
    batch_size: 64
    model: "@dip_vae()" #"@HsicBetaVAE()"  #"@vae()"
    training_steps: 100000
  dip_vae:
    alpha: 100
    #beta: 4
    lambda_od: 5.0
    lambda_d_factor: 1.0
    dip_type: "\"ii\""
    s_x: 100
    s_y: 100
    num_sample_reparam: 3
  out_dir: "/home/wliang/miniconda3/envs/tf/lib/python3.7/site-packages/disentanglement_lib/src/results/noisy_dsprites/2022Oct01-202519_train_hsicdipvae"
  run_id: 0
  folder_num: '0006_'