train:
  model:
    name: "\"annealed_vae\"" #"HsicBetaVAE"
    batch_size: 64
    eval_steps: 1000
    model: "@annealed_vae()" #"@HsicBetaVAE()"  #"@vae()"
    training_steps: 200000
  annealed_vae:
    alpha: 10.
    c_max: 75.0
    gamma: 1000
    iteration_threshold: 100000
    s_x: 100
    s_y: 100
    num_sample_reparam: 3
  bernoulli_loss:
    subtract_true_image_entropy: False
  encoder:
    num_latent: 10
    encoder_fn: "@conv_encoder"
  decoder:
    decoder_fn: "@deconv_decoder"
  discriminator_optimizer:
    optimizer_fn: "@discriminator/AdamOptimizer"
  discriminator/AdamOptimizer:
    beta1: 0.5
    beta2: 0.9
    epsilon: 0.00000001
    learning_rate: 0.0001
    name: "\"Adam\""
    use_locking: False
  vae_optimizer:
    optimizer_fn: "@vae/AdamOptimizer"
    learning_rate: None
  vae/AdamOptimizer:
    beta1: 0.9
    beta2: 0.999
    epsilon: 0.00000001
    learning_rate: 0.0001
    name: "\"Adam\""
    use_locking: False
  reconstruction_loss:
    loss_fn: "@bernoulli_loss"
    activation: "\"logits\""
  dataset:
    name: "\"cars3d\"" #"\"dsprites_full\""
  export_as_tf_hub:
    drop_collections: None